---
## Where to find your cert and cert key
ssl_certs_source: "{{ playbook_dir }}/files"

## location for the container persistent storage
## this location should have at least 8G of
## available storage or you can specify a
## different path for the data dir with
## container_data_dir
container_dir: "/opt/containers/registry"

## data directory for mirrored content storage location
container_data_dir: "{{ container_dir }}/data"

## Default names for self generated key and cert
ssl_key_filename: "{{ registry_hostname }}.key"
ssl_cert_filename: "{{ registry_hostname }}.crt"
ssl_csr_filename: "{{ registry_hostname }}.csr"

## Full path to cert key and certificate
ssl_cert_file: "{{ ssl_certs_source }}/{{ ssl_cert_filename }}"
ssl_key_file: "{{ ssl_certs_source }}/{{ ssl_key_filename }}"
ssl_csr_file: "{{ ssl_certs_source }}/{{ ssl_csr_filename }}"

## Podman container certs.d
containers_certs_d: "/etc/containers/certs.d/{{ registry_fqdn }}:{{ registry_port }}"

## Should we generate a self signed cert?
## no - if you are providing your own otherwise - yes
## make sure to provide the ssl_cert_filename and ssl_cert_file
generate_self_signed_certs: yes

## Registry FQDN
registry_domain: lab.qubinode.io

## Registry hostname
registry_hostname: registry

## Registry IP address
registry_ip: 192.168.8.9

## Registry FQDN
registry_fqdn: "{{ registry_hostname }}.{{ registry_domain }}"

## Port to expose the registry on
registry_port: 5000

## Local registry auth file
registry_local_auth: "WOmpBat"

## OpenShift pull-secret
pull_secret: "/home/admin/qubinode-installer/pull-secret.txt"

## Generated pull-secret.json path
generated_pull_secret: "/home/admin/qubinode-installer/generated_pullsecret.json"

## additional_trust_bundle
additional_trust_bundle: /home/admin/qubinode-installer/trust-bundle.txt
image_content_sources: /home/admin/qubinode-installer//content-sources.txt

## user and group to own the container_dir
container_user: admin
container_group: admin

## Options to for CSR
self_signed_certs_options:
    cert_country: "US"
    cert_state: "FL"
    cert_locality: "Orange"
    cert_org_name: "Qubinode"
    cert_org_unit: "Lab"
    cert_common_name: "{{ registry_fqdn }}"
    cert_subject_alt_name: "DNS:{{ registry_fqdn }},IP:{{ registry_ip }}"

## we use htpasswd to setup user to access the registry container
registry_username: regadmin
registry_password: regadmin

## Set this option to absent to delete the registry container
container_state: present

## no need to change the below
update_trust_file_name: "/etc/pki/ca-trust/source/anchors/{{ registry_hostname }}.crt"
