---
- name: prereqs for registry
  tags: [registry_prereq, deploy_registry]
  become: yes
  block:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0775'
        owner: "{{ container_user }}"
        group: "{{ container_group }}"
      loop:
        - "{{ container_dir }}/auth"
        - "{{ container_dir }}/certs"
        - "{{ containers_certs_d }}"

    - name: ensure cert files are copied to {{ containers_certs_d }}
      copy:
        src: "{{ ssl_certs_source }}/{{ item }}"
        dest: "{{ containers_certs_d }}/{{ item }}"
        mode: 0644
      loop:
        - "{{ ssl_key_filename }}"
        - "{{ ssl_cert_filename }}"

    - name: ensure certs are copied to {{ container_dir }} certs dir
      copy:
        src: "{{ ssl_certs_source }}/{{ item }}"
        dest: "{{ container_dir }}/certs"
        mode: 0644
      loop:
        - "{{ ssl_key_filename }}"
        - "{{ ssl_cert_filename }}"

    - name: open ports for registry
      firewalld:
        port: "{{ registry_port }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled

    - name: rename {{ ssl_cert_filename }} to have cert suffix
      copy:
        src: "{{ ssl_cert_file }}"
        dest: "{{ containers_certs_d }}/{{ registry_fqdn }}.cert"
        mode: 0644
      ignore_errors: yes

- name: create random secret for container registry
  set_fact:
    registry_http_secret: "{{ lookup('password', secret_file + ' ' + 'chars=ascii_letters') }}"
  tags: [ registry, deploy_registry ]

- name: install pip packages
  pip:
    name: "{{ item }}"
    extra_args: --user
  loop:
    - passlib
    - bcrypt
  tags: [packages, pip, deploy_registry]

- name: create htpasswd user for registry container
  htpasswd:
    state: present
    path: "{{ container_dir }}/auth/htpasswd"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    owner: "{{ container_user }}"
    group: "{{ container_group }}"
    mode: 0640
    crypt_scheme: bcrypt
  tags: [setup_htpasswd, deploy_registry]

## Future task is to put this all into a single pod
## with something like nginx or haproxy
- name: create-registry.yml - Deploy registry containers
  include_tasks: registries.yml
  loop: "{{ registry_pods }}"
  loop_control:
    loop_var: outer_item
    label: outer_item.name
  tags: [ registry_container_state, container, registry, deploy_registry ]